backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img/uploads
public_folder: /img/uploads

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'content/pages/cms-static-page.md'
        label: 'CMS Static Page'
        name: 'cms-static-page'
        fields:
          - { label: 'Template Key', name: 'templateKey', widget: 'hidden', default: 'cms-static-page' }
          - {
              label: Metadata,
              name: metadata,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: string },
                  { label: URL, name: url, widget: string },
                  { label: Image, name: image, widget: image },
                ],
            }
          - { label: Invert content order, name: invertContent, widget: boolean, default: false }
          - {
              label: Hero,
              name: hero,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: string },
                  { label: CTA Text, name: ctaText, widget: string },
                  { label: CTA Href, name: ctaHref, widget: string },
                ],
            }
          - {
              label: CardSection,
              name: cardSection,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Subtitle, name: subtitle, widget: string, required: false },
                  {
                    label: Cards,
                    name: cards,
                    widget: list,
                    fields:
                      [
                        { label: Icon, name: icon, widget: image, required: false },
                        { label: Title, name: title, widget: string },
                        { label: Content, name: content, widget: string },
                      ],
                  },
                ],
            }
          - {
              label: Blocks,
              name: blocks,
              widget: list,
              fields:
                [
                  { label: Image, name: image, widget: image },
                  { label: Subheader, name: subheader, widget: string },
                  { label: Content, name: content, widget: string },
                  { label: Is image after text, name: isImageAfterText, widget: boolean },
                  { label: CTA text, name: ctaText, widget: string },
                  { label: CTA url, name: ctaUrl, widget: string },
                  { label: Is CTA a primary button, name: isCtaButton, widget: boolean },
                ],
            }
          - {
              label: Inline CTA,
              name: inlineCta,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Subtitle, name: subtitle, widget: string },
                  { label: Button text, name: buttonText, widget: string },
                  { label: Button href, name: buttonHref, widget: string },
                ],
            }
