name: CI
on: [push]
jobs:
  setup:
    name: run yarn, build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: yarn install
        - uses: bahmutov/npm-install@v1
          with:
            install-command: yarn
      - name: yarn build
          run: yarn run build

  lighthouse:
    name: run Lighthouse CI
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: run Lighthouse CI
        run: |
          yarn global add @lhci/cli@0.6.x
          export PATH=$(yarn global bin):$PATH
          lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

  linters:
    name: run eslint, prettier
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: run linters
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          eslint: true
          prettier: true

  bundlewatch:
    name: run bundlewatch
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: run bundlewatch
        run: yarn run bundlewatch
        env:
          BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
